apiVersion: v2
description: A Helm chart for deploying Flink applications using FlinkDeployment CRD
  from flink-kubernetes-operator.
icon: https://flink.apache.org/img/logo/png/50/color_50.png
name: aggregator
type: application
version: 0.4.9
dependencies:
- name: flink
  version: 0.4.9
  repository: file://charts/flink
  alias: aggregator_5g
  condition: aggregator_5g.enabled
- name: flink
  version: 0.4.9
  repository: file://charts/flink
  alias: aggregator_6g
  condition: aggregator_6g.enabled
- name: flink
  version: 0.4.9
  repository: file://charts/flink
  alias: ecds-pnw-carrierkpi-4g-stats-prod
  condition: ecds-pnw-carrierkpi-4g-stats-prod.enabled
- name: flink
  version: 0.4.9
  repository: file://charts/flink
  alias: aggregator_alarm
  condition: aggregator_alarm.enabled