apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  {{- include "meta.metadata" (dict "Root" .) | indent 2 }}

spec:
  image: {{ .Values.app.image }}:{{ .Values.app.version }}
  imagePullPolicy: {{ .Values.docker.pull_policy }}
  flinkVersion: {{ .Values.app.flinkVersion }}
  {{- if .Values.ingress.enabled }}
  ingress:
    annotations:
      route.openshift.io/termination: edge  
    template: "{{- include "meta.name" (dict "Root" .) }}-{{.Values.app.podmonitor.matchnamespace }}.{{.Values.ingress.clustersuffix}}"  
  {{ end }}
  # mode: native
  {{- /*
  NOTE: serviceAccount must match the ServiceAccount created by
  flink-kubernetes-operator from .Values.jobServiceAccount.name.
  */}}
  serviceAccount: flink
  restartNonce: {{ .Values.app.restartNonce | default 1 }}

  job:
    {{- with .Values.app.job | default dict }}
    {{- /*
    app.job.pythonEntryPoint is sugar to abstract JobSpec params for launching Flink Python jobs.
    If app.job.pythonEntryPoint is set, entryClass and args will be set appropriately.
    */}}
    {{- if .pythonEntryPoint }}
    entryClass: org.apache.flink.client.python.PythonDriver
    {{- $args := concat (list "-py" .pythonEntryPoint ) .args }}
    {{- $jobSpec := merge (dict "args" $args) . }}
    {{- $_ := unset $jobSpec "pythonEntryPoint" }}
    {{- (toYaml $jobSpec ) | nindent 4 }}
    {{- else }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}

  logConfiguration:
    "log4j-console.properties": |
      {{- if .Values.app.logConfiguration }}
      {{- range $key, $val := .Values.app.logConfiguration }}
      {{ $key }} = {{ $val }}
      {{- end }}
      {{- end }}

  flinkConfiguration:
    {{- if .Values.app.flinkConfiguration }}
    ### User provided configuration
    # flinkConfiguration must be map of str: str.
    # Iterate through and quote the values, in case they look like integers.
    {{- range $key, $val := .Values.app.flinkConfiguration }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- end }}

  # Use podTemplate to add WMF labels and annotations to all pods.
  # https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-main/docs/custom-resource/pod-template/
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        {{- include "meta.pod_labels" . | indent 8 }}
      annotations:
        {{- include "meta.pod_annotations" . | indent 8 }}
    {{- if or .Values.app.env .Values.app.config_files }}
    spec:
      containers:
        {{- if or .Values.app.env .Values.app.config_files}}
        - name: flink-main-container
          imagePullPolicy: Always
          securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                  drop: ["ALL"]
              seccompProfile:
                  type: RuntimeDefault
              readOnlyRootFilesystem: true
          {{- if or .Values.app.env }}
          env:
            {{- if .Values.app.env | default false }}
            {{- toYaml .Values.app.env | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.app.envfrom | default false }}
            {{- toYaml .Values.app.envfrom | nindent 12 }}
            {{- end }}
          {{- end }} # end env
          volumeMounts:
            {{- if .Values.app.volumemount | default false }}
            {{- toYaml .Values.app.volumemount | nindent 12 }}
            {{- end }}
        {{- end }} # end flink-main-container

      volumes:
            {{- if .Values.app.volumes | default false }}
            {{- toYaml .Values.app.volumes | nindent 8 }}
            {{- end }}
    {{- end }} # end spec

  jobManager:
    {{- toYaml .Values.app.jobManager | nindent 4 }}

  taskManager:
    {{- toYaml .Values.app.taskManager | nindent 4 }}

