{{- if .Values.app.podmonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "name.release" . }}-pm
  labels:
    app: {{ template "name.chart" . }}
    chart: {{ template "name.chartid" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.app.podmonitor.matchnamespace }}
  podMetricsEndpoints:
    - path: /metrics
      relabelings:
        - action: replace
          replacement: '$1:9249'
          sourceLabels:
            - __meta_kubernetes_pod_ip
          targetLabel: __address__
  selector:
    matchLabels:
{{- include "meta.labels" . | indent 6 }}
{{- end }}
