---
# Source: flink/templates/flink-template.yaml
apiVersion: flink.k8s.io/v1alpha1
kind: FlinkCluster
metadata:
  name: ecds-carrieragg4g-graph
  namespace: gulv-dev-aggregator
spec:
  image: gulv-space-rtt-docker-np.oneartifactoryci.verizon.com/build-images/rttflink:9c38a804
  flinkVersion: v1_17
  flinkConfiguration:
    heartbeat.timeout: 50000
    restart-strategy.exponential-delay.backoff-multiplier: 2.0
    restart-strategy.exponential-delay.initial-backoff: 1 s
    restart-strategy.exponential-delay.jitter-factor: 0.1
    restart-strategy.exponential-delay.max-backoff: 5 min
    restart-strategy.exponential-delay.reset-backoff-threshold: 30 min
    restart-strategy.type: exponential-delay
    taskmanager.memory.jvm-metaspace.size: 1024m
    taskmanager.memory.task.off-heap.size: 128m
    taskmanager.numberOfTaskSlots: 10
  serviceAccount: 
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: ecds-carrieragg4g-graph
      name: flink-ecds-carrieragg4g-graph
    spec:
      containers:
        - name: flink-main-container
          imagePullPolicy: Always 
          envFrom:
            - configMapRef:
                name: flink-aggregator-dev
            - secretRef:
                name: flink-aggregator-dev
          env:
            - name: FLINK_JOB_NAME
              value: ecds-carrieragg4g-graph
          volumeMounts:
            - mountPath: /certs/cospd3-kafkacert.pem
              name: kafka-certs
              subPath: cospd3-kafkacert.pem
      volumes:
        - name: kafka-certs
          secret:
            defaultMode: 420
            secretName: kafka-certs
  jobManager:
    resource:
      memory: 2048m
      cpu: 1
  taskManager:
    resource:
      memory: 15G
      cpu: 1
  job:  
    args: [--inputJson /flink-json-configs/ECDS/4G/ecds-carrierkpis-4g-graph.json]
    entryClass: com.vzw.aggregator.Aggregator_v2
    jarURI: local:///opt/flink/usrlib/flinkaggregator-bundled-0.1.jar
    parallelism: 100
    upgradeMode: stateless
