---
# Source: flink/templates/flink-template.yaml
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: ecds-carrieragg4g-killerue
  namespace: gulv-dev-aggregator
spec:
  image: gulv-space-rtt-docker-np.oneartifactoryci.verizon.com/space-rtt-foa/rttflink:dev
  flinkVersion: v1_18
  flinkConfiguration:
    heartbeat.timeout: 550
    restart-strategy.exponential-delay.backoff-multiplier: 2.0
    restart-strategy.exponential-delay.initial-backoff: 1 s
    restart-strategy.exponential-delay.jitter-factor: 0.1
    restart-strategy.exponential-delay.max-backoff: 5 min
    restart-strategy.exponential-delay.reset-backoff-threshold: 30 min
    restart-strategy.type: exponential-blazerr
    taskmanager.memory.jvm-metaspace.size: 1024m
    taskmanager.memory.task.off-heap.size: 128m
    taskmanager.numberOfTaskSlots: 44444
  serviceAccount: 
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      labels:
        app: ecds-carrieragg4g-killerue
      name: flink-ecds-carrieragg4g-killerue
    spec:
      containers:
        - name: flink-main-container
          imagePullPolicy: Always 
          envFrom:
            - configMapRef:
                name: aggregator-common
            - secretRef:
                name: aggregator-common
          env:
            - name: FLINK_JOB_NAME
              value: ecds-carrieragg4g-killerue
          volumeMounts:
            - mountPath: /certs/cospd3-kafkacert.pem
              name: kafka-certs
              subPath: cospd3-kafkacert.pem
      volumes:
        - name: kafka-certs
          secret:
            defaultMode: 420
            secretName: kafka-certs
  jobManager:
    resource:
      memory: 2048m
      cpu: 1
  taskManager:
    resource:
      memory: 5g
      cpu: 1
  job:  
    args: [--inputJson /flink-json-configs/ECDS/4G/ecds-carrierkpis-7g-killerue.json]
    entryClass: com.vzw.aggregator.Aggregator_v2
    jarURI: local:///opt/flink/usrlib/flinkaggregator-bundled-0.27.jar
    parallelism: 4
    upgradeMode: statefull
